<a href="https://colab.research.google.com/github/sojldatascientist/ECS/blob/master/Correction_Examen_Numpy_ECS1_session_avril2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd, numpy as np

In [2]:
# Utilisons un dictionnaire
dico = { 'Surname' : ['MAHEY']*6, 'Forename/Initials' : ['Husan L', 'Priya', 'Sonam','Ravinder RL','Sunita K','Manisha'] }
dico1 = { 'Surname' : ['MAHEY','MOY','MAHEY','MIGUL','MAHEY','NISHANY'], 'Forename/Initials' : ['Husan L', 'Priya', 'Sonam','Ravinder RL','Sunita K','Manisha'] }

In [3]:
#df = pd.DataFrame(dico)
df = pd.DataFrame(dico1)  # données de type dataframe

In [4]:
df

Surname Forename/Initials
0    MAHEY           Husan L
1      MOY             Priya
2    MAHEY             Sonam
3    MIGUL       Ravinder RL
4    MAHEY          Sunita K
5  NISHANY           Manisha

In [5]:
df.values

array([['MAHEY', 'Husan L'],
       ['MOY', 'Priya'],
       ['MAHEY', 'Sonam'],
       ['MIGUL', 'Ravinder RL'],
       ['MAHEY', 'Sunita K'],
       ['NISHANY', 'Manisha']], dtype=object)

In [6]:
Nom = "MAHEY"

transf = lambda nom : [ord(c)%100 for c in nom ] if len(nom) == 6 else  [0]*(6 - len(nom)%6) + [ord(c)%100 for c in nom ]
transf(Nom)

[0, 77, 65, 72, 69, 89]

In [7]:
sum(transf(Nom))

372

In [8]:
df1 = df.copy()  # copie propre de df

In [9]:
df1.columns # les colonnes de df1

Index(['Surname', 'Forename/Initials'], dtype='object')

In [10]:
# Transformation des données
df1.rename(columns = {'Forename/Initials': 'Forename'}, inplace = True)
df1['Initials'] = df1.Forename.apply(lambda x : x.split()[1] if len(x.split()) == 2 else str(0) )
df1['Forename'] = df1.Forename.apply(lambda x : x.split()[0] )

df1

Surname  Forename Initials
0    MAHEY     Husan        L
1      MOY     Priya        0
2    MAHEY     Sonam        0
3    MIGUL  Ravinder       RL
4    MAHEY    Sunita        K
5  NISHANY   Manisha        0

In [11]:
transfx = lambda nom : [ord(c)%100 for c in str(nom) ] if len(str(nom)) == 6 else  [0]*(6 - len(str(nom))%6) + [ord(c)%100 for c in str(nom) ]
transfx(1) # une fonction pour obtenir une liste de valeurs ascii avec les conditions énuméréés.

[0, 0, 0, 0, 0, 49]

In [12]:
transf = lambda nom : sum([ord(c)%100 for c in str(nom) ]) if len(str(nom)) == 6 else  sum([0]*(6 - len(str(nom))%6) + [ord(c)%100 for c in str(nom) ])
transf(1) # Cette fois ci, la somme est considéréé

49

In [13]:
# Application de la transformation
df1.Forename = df1.Forename.apply( lambda col : sum(transfx(col)))
df1.Initials = df1.Initials.apply( lambda col : sum(transfx(col)))
df1.Surname = df1.Surname.apply( lambda col : sum(transfx(col)))
df1

Surname  Forename  Initials
0      372       211        76
1      245       217        48
2      372       210        48
3      382       227       158
4      372       228        75
5      538       305        48

In [14]:
df1.values # Valeurs numériques dans la forme d'un tableau

array([[372, 211,  76],
       [245, 217,  48],
       [372, 210,  48],
       [382, 227, 158],
       [372, 228,  75],
       [538, 305,  48]])

In [15]:
N = df1.values # N est la donnée demandeée

In [16]:
N

array([[372, 211,  76],
       [245, 217,  48],
       [372, 210,  48],
       [382, 227, 158],
       [372, 228,  75],
       [538, 305,  48]])

In [17]:
N.shape # taille de N

(6, 3)

In [18]:
# Correctif apporté aux valeurs : 48 de la 3e colonne
N[1,2] = 51
N[2,2] = 50
N[5,2] = 50

In [19]:
N = np.column_stack((N,np.min(N, axis = 1) + np.max(N, axis = 1))) # Rajout d'une nouvelle colonne avec les conditions énoncées
N

array([[372, 211,  76, 448],
       [245, 217,  51, 296],
       [372, 210,  50, 422],
       [382, 227, 158, 540],
       [372, 228,  75, 447],
       [538, 305,  50, 588]])

In [20]:
premier = lambda x : sum( [1 if x%i == 0 else 0 for i in range(1,x+1) ]) == 2
premier(60)

False

In [21]:
# Les fonctions suivantes ont été définies

In [22]:
def premierInf (nbre) :
  if premier(nbre) :
    return nbre
  else :
    while( premier(nbre) == False ) :
      nbre = nbre - 1
    return nbre

def premierSuiv (nbre) :
  if premier(nbre) :
    return nbre
  else :
    while( premier(nbre) == False ) :
      nbre = nbre + 1
    return nbre

def premierStrictSuiv (nbre) :
  if premier(nbre) :
    nbre = nbre + 1
    return premierSuiv (nbre)
  else :
    while( premier(nbre) == False ) :
      nbre = nbre + 1
    return nbre


In [23]:
print(premierInf(366))
print(premierSuiv(366))
print(premierStrictSuiv(366))


359
367
367


In [24]:
print(premierInf(367))
print(premierSuiv(367))
print(premierStrictSuiv(367))

367
367
373


In [25]:
M = N.copy()  # application de la fonction premierInf avec les conditions énoncées
for i in range(len(M)) :
  for j in range(N.shape[1]):
    M[i,j] = premierInf(N[i][j])

In [26]:
M

array([[367, 211,  73, 443],
       [241, 211,  47, 293],
       [367, 199,  47, 421],
       [379, 227, 157, 523],
       [367, 227,  73, 443],
       [523, 293,  47, 587]])

P ou T renvoie à la même valeur

In [27]:
P = M.copy()  # application de la fonction premierStrictSuiv avec les conditions énoncées
for i in range(len(P)):
  for j in range(P.shape[1]):
    m = int(np.median(M[:,j], axis = 0))
    conditionInf = P[:,j] < m
    P[:,j] = np.where(conditionInf, premierStrictSuiv(m) ,P[:,j])
P

array([[367, 223,  73, 443],
       [373, 223,  61, 449],
       [367, 223,  61, 449],
       [379, 227, 157, 523],
       [367, 227,  73, 443],
       [523, 293,  61, 587]])

In [28]:
# Calculer la médiane de chaque colonne

T = M.copy()
medianes_colonnes = np.median(M, axis=0)

# Parcourir les colonnes et remplacer les valeurs inférieures à la médiane
for i in range(T.shape[1]):
    mediane_colonne = medianes_colonnes[i]
    for j in range(T.shape[0]):
        if T[j, i] < mediane_colonne:
            T[j, i] = premierStrictSuiv(int(mediane_colonne))
T

array([[367, 223,  73, 443],
       [373, 223,  61, 449],
       [367, 223,  61, 449],
       [379, 227, 157, 523],
       [367, 227,  73, 443],
       [523, 293,  61, 587]])